# Generated by Django 5.1.2 on 2024-10-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_ticket_user_alter_ticket_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
    ]
