# Generated by Django 5.1.2 on 2024-10-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_review_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="time_created",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="data_created",
            new_name="date_created",
        ),
    ]
